trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'healthcare-app'
  tag: 'latest'

  acrServiceConnection: 'acr-Docker-healthcare'
  azureServiceConnection: 'azure-rm-healthcare'
  sonarServiceConnection: 'healthcare-SonarQube'

stages:

# ==================================================
# STAGE 1: VALIDATE
# ==================================================
- stage: Validate
  displayName: 'Validate Code'

  jobs:
  - job: Validation
    displayName: 'Lint, Test & SonarQube'

    steps:

    - checkout: self

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'

    - script: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install flake8 pytest
      displayName: 'Install Dependencies'

    # SonarQube Prepare
    - task: SonarQubePrepare@7
      displayName: 'Prepare SonarQube Analysis'
      inputs:
        SonarQube: 'healthcare-SonarQube'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: 'healthcare-app'
        cliProjectName: 'healthcare-app'

    # Lint
    - script: |
        flake8 app/
      displayName: 'Lint Check'

    # Unit Tests
    - script: |
        export PYTHONPATH=$(Build.SourcesDirectory)
        pytest tests/ -v
      displayName: 'Run Unit Tests'

    # SonarQube Analyze
    - task: SonarQubeAnalyze@7
      displayName: 'Run SonarQube Analysis'

    # SonarQube Publish
    - task: SonarQubePublish@7
      displayName: 'Publish SonarQube Results'
      inputs:
        pollingTimeoutSec: '300'


# ==================================================
# STAGE 2: BUILD DOCKER IMAGE
# ==================================================
- stage: Build
  displayName: 'Build Docker Image'
  dependsOn: Validate

  jobs:
  - job: DockerBuild
    displayName: 'Build Docker Image'

    steps:

    - checkout: self

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: build
        repository: $(imageName)
        Dockerfile: app/Dockerfile
        tags: |
          $(tag)

    - script: |
        docker images
      displayName: 'Verify Docker Image'


# ==================================================
# STAGE 3: TRIVY SECURITY SCAN
# ==================================================
- stage: SecurityScan
  displayName: 'Container Security Scan'
  dependsOn: Build

  jobs:
  - job: TrivyScan
    displayName: 'Scan Docker Image'

    steps:

    - script: |
        sudo apt-get update
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.65.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.65.0_Linux-64bit.deb
      displayName: 'Install Trivy'

    - script: |
        trivy image --exit-code 0 healthcare-app:latest
      displayName: 'Generate Trivy Report'

    - script: |
        trivy image --exit-code 1 --severity CRITICAL healthcare-app:latest
      displayName: 'Fail on Critical Vulnerabilities'


# ==================================================
# STAGE 4: PUSH IMAGE TO ACR
# ==================================================
- stage: PushToACR
  displayName: 'Push Image to ACR'
  dependsOn: SecurityScan

  jobs:
  - job: PushImage
    displayName: 'Push Docker Image'

    steps:

    - checkout: self

    - task: Docker@2
      displayName: 'Build and Push Image'
      inputs:
        command: buildAndPush
        containerRegistry: 'acr-Docker-healthcare'
        repository: $(imageName)
        Dockerfile: app/Dockerfile
        tags: |
          $(tag)
