trigger:
- Master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'healthcare-app'
  tag: 'latest'

  acrServiceConnection: 'acr-docker-healthcare-sp'

  sonarProjectKey: 'healthcare_app_project1'
  sonarProjectName: 'Healthcare App'

stages:

# =====================================================
# STAGE 1 - VALIDATE
# =====================================================

- stage: Validate
  displayName: 'Validate Code'

  jobs:
  - job: Validation
    displayName: 'Lint Test SonarQube'

    steps:

    - checkout: self

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.11'

    - script: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install pytest flake8
      displayName: 'Install Dependencies'

    - task: SonarQubePrepare@7
      displayName: 'Prepare SonarQube'
      inputs:
        SonarQube: 'sonarqube-project1'
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: '$(sonarProjectKey)'
        cliProjectName: '$(sonarProjectName)'

    - script: |
        flake8 app/
      displayName: 'Run Flake8'

    - script: |
        export PYTHONPATH=$(Build.SourcesDirectory)
        pytest tests/ -v
      displayName: 'Run Pytest'

    - task: SonarQubeAnalyze@7
      displayName: 'Analyze Code'

    - task: SonarQubePublish@7
      displayName: 'Publish SonarQube Results'
      inputs:
        pollingTimeoutSec: '300'

# =====================================================
# STAGE 2 - BUILD AND SCAN
# =====================================================

- stage: Build
  displayName: 'Build And Scan'
  dependsOn: Validate

  jobs:
  - job: DockerBuild
    displayName: 'Build Docker Image'

    steps:

    - checkout: self

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        repository: '$(imageName)'
        Dockerfile: 'app/Dockerfile'
        tags: |
          $(tag)

    - script: |
        docker images
      displayName: 'Verify Docker Image'

    - script: |
        sudo apt-get update
        sudo apt-get install wget -y

        wget -qO- https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

        trivy --version
      displayName: 'Install Trivy'

    - script: |
        trivy image --exit-code 0 $(imageName):$(tag)
      displayName: 'Generate Trivy Report'

# =====================================================
# STAGE 3 - PUSH IMAGE TO ACR
# =====================================================

- stage: PushToACR
  displayName: 'Push Image To ACR'
  dependsOn: Build

  jobs:
  - job: PushImage
    displayName: 'Push Docker Image'

    steps:

    - checkout: self

    - task: Docker@2
      displayName: 'Build And Push Image'
      inputs:
        command: 'buildAndPush'
        containerRegistry: '$(acrServiceConnection)'
        repository: '$(imageName)'
        Dockerfile: 'app/Dockerfile'
        tags: |
          $(tag)